// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appConsola;

#nullable disable

namespace appConsola.Migrations
{
    [DbContext(typeof(TurjoyContext))]
    [Migration("20241129165725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("appConsola.Bus", b =>
                {
                    b.Property<int>("IdBus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idBus");

                    b.Property<string>("CodigoBus")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("codigoBus");

                    b.Property<string>("EsHabilitado")
                        .HasColumnType("longtext")
                        .HasColumnName("esHabilitado");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int")
                        .HasColumnName("kilometraje");

                    b.HasKey("IdBus")
                        .HasName("PRIMARY");

                    b.ToTable("bus", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
